# azure-pipelines-web.yml
trigger: { branches: { include: [ main ] } }
pr:       { branches: { include: [ main ] } }

variables:
  # 镜像（web）
  webRepo: 'docker.io/rayrayye/timeapp-web'
  dockerfilePath: 'Dockerfile'
  buildContext: '.'

  # 配置仓（org/repo）和路径（注意带 &）
  githubOrgRepo: 'RookieToExpert/az305'
  configPath: 'kubernetes&docker/timeapp-config/overlays/prod'

  # 版本号（web 独立计数）
  major: '1'
  counterKey: 'web-1'
  patch: $[ counter(variables['counterKey'], 0) ]
  version: '$(major).$(patch)'

stages:
# ---------- Build & Push ----------
- stage: Build
  displayName: Build & Push (web)
  jobs:
  - job: build
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - task: Docker@2
      displayName: Login Docker Hub
      inputs: { command: login, containerRegistry: 'toDockerHub' }   # ← 你的 Docker Hub service connection
    - task: Docker@2
      displayName: Build+Push web:$(version)
      inputs:
        command: buildAndPush
        repository: '$(webRepo)'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(buildContext)'
        tags: |
          $(version)

# ---------- Create PR to config repo ----------
- stage: ConfigPR
  displayName: Create PR (bump web tag)
  dependsOn: Build
  jobs:
  - job: pr
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - checkout: none

    # yq + jq（改 YAML、解析 PR 响应）
    - script: |
        set -euo pipefail
        curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
        chmod +x /usr/local/bin/yq
        sudo apt-get update -y
        sudo apt-get install -y jq
      displayName: Install yq & jq

    - script: |
        set -euo pipefail

        git config --global user.name  "ado-bot"
        git config --global user.email "ado-bot@example.com"

        # 1) 用 PAT 克隆配置仓（用 $GITHUB_TOKEN，不要写 $(...)）
        GIT_URL="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git"
        git clone "$GIT_URL" configrepo
        cd configrepo

        # 2) 新建分支
        BR="bump-web-${VERSION}-${BUILD_ID}"
        git switch -c "$BR"

        # 3) 改 Kustomize 的镜像 tag（只改 web）
        FILE="${CONFIG_PATH}/kustomization.yaml"
        yq -i '(.images[] | select(.name == env(IMG_NAME))).newTag = env(VERSION)' "$FILE"

        git add "$FILE"
        git commit -m "chore(web): bump to ${VERSION}"
        git push -u origin "$BR"

        # 4) 用 REST API 创建 PR 并打印链接
        RESP=$(curl -sS -X POST "https://api.github.com/repos/${GITHUB_REPO}/pulls" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github+json" \
          -d "{\"title\":\"Bump web to ${VERSION}\",\"body\":\"Update web image tag to ${VERSION} for GitOps\",\"head\":\"$BR\",\"base\":\"main\",\"maintainer_can_modify\":true}")
        echo "$RESP" | jq -r '.html_url'

        # （可选）自动合并：分支保护允许时再打开下面两行
        # PR_NUM=$(echo "$RESP" | jq -r '.number')
        # curl -sS -X PUT "https://api.github.com/repos/${GITHUB_REPO}/pulls/${PR_NUM}/merge" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" -d '{"merge_method":"merge"}'
      displayName: 'Bump web tag & open PR'
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)                      # ← DevOps Secret 变量
        GITHUB_REPO: $(githubOrgRepo)
        CONFIG_PATH: '$(configPath)'
        IMG_NAME: '$(webRepo)'
        VERSION: $(version)
        BUILD_ID: $(Build.BuildId)
